### PR TITLE
Removing more QVector from core

### PR DESCRIPTION
**Pull request by sakertooth**
Removes the remaining ``QVector`` from the core and makes the necessary changes to non-core components. I plan on doing a small reorganization of the core so it is easier to know what to change and what not to change.

I am submitting it to your original Qt removal PR. I do not think it is best to make distinct PRs for a single goal, but that is just me. This builds off of your QVector removal PR.

I have tested the code and it seems to compile and build. ~I still have to make some changes so that it complies with the CI tests,~ but the changes, I believe, are indeed functional and working.

Core components still in need of QVector removal:
- [x] ``ConfigManager``

### CODE REVIEW

**Comment by Veratil** [comment]
Can you go through the lines that you've changed and fix the style?

[For instance here](https://github.com/Veratil/lmms/pull/6/commits/46d2f999eb1db0b73197ce2fb07b5d71761c767d#diff-e9bc3866766f77eab76084d28eb3b8861574375e132403804d72e9a7ebf79fdeR71) remove the spaces in `( this )` to make it `(this)`.

**Comment by sakertooth** [comment]
> Can you go through the lines that you've changed and fix the style?
> 
> 
> 
> [For instance here](https://github.com/Veratil/lmms/pull/6/commits/46d2f999eb1db0b73197ce2fb07b5d71761c767d#diff-e9bc3866766f77eab76084d28eb3b8861574375e132403804d72e9a7ebf79fdeR71) remove the spaces in `( this )` to make it `(this)`.

I was planning to do a full reorganization of files and reformatting of the source in a separate PR for the core. Should I just reformat along the way and worry about reorganizing stuff later?

**Comment by Veratil** [comment]
Also, have you compiled and ran lmms with these changes? Open demos and play them, etc?

**Comment by Veratil** [comment]
> I was planning to do a full reorganization of files and reformatting of the source in a separate PR for the core. Should I just reformat along the way and worry about reorganizing stuff later?

Fix things up as we go through and change lines is generally the way we've done it.

**Comment by sakertooth** [comment]
> Also, have you compiled and ran lmms with these changes? Open demos and play them, etc?

The changes were successfully compiled and built. I did some tests and everything is practically functional. Tested the demos, made some patterns, and all the sounds are working as expected.

> Fix things up as we go through and change lines is generally the way we've done it.

I mean, a majority of the codebase needs reformatting, and it won't take me too long to reformat the whole core (VSCode makes this fairly simple). If I am going to format my changes, why not format everything else that needs it? :smile:

**Comment by Veratil** [comment]
> The changes were successfully compiled and built. I did some tests and everything is practically functional. Tested the demos, made some patterns, and all the sounds are working as expected.

Good! That's all we really need to check for the most part. If anything bad would happen it would most likely happen during a demo load/play/unload.

> I mean, a majority of the codebase needs reformatting, and it won't take me too long to reformat the whole core (VSCode makes this fairly simple). If I am going to format my changes, why not format everything else that needs it? 😄

Yeah but that adds unrelated changes to the PR, and history of my own wants to do this have been met with "just change the style on lines you fix/add". Trust me, I'd really like to just go through and reformat stuff, too. lol

**Comment by sakertooth** [comment]
~I think all that is left is to sort out ``ConfigManager``. It is segfaulting when switching ``stringPairVector`` to use a ``std::vector``.~ Let me know if you find anything else that needs work.

Done.

**Comment by Veratil** [comment]
Did we not have to add `#include <vector>` to some headers? I notice in ConfigManager you changed to `std::vector` but there's no include for vector.

**Comment by sakertooth** [comment]
> Did we not have to add `#include <vector>` to some headers? I notice in ConfigManager you changed to `std::vector` but there's no include for vector.

Could be a good reason to start using ``include-what-you-use`` ~but I'll manually check for any ``#include <QVector>``'s that aren't needed in the core for now.~ (realized I can run it without plugging it into the build system :sweat_smile:)

**Comment by Veratil** [comment]
Double checked build, looks good so far. Anything else or shall I merge?

**Comment by sakertooth** [comment]
> Double checked build, looks good so far. Anything else or shall I merge?

I personally think its good to go. If anything, we can make fixes along the way.

**Pull request merged**
